Allow providing `amount` when creating Hasher from checksum.
srijs/rust-crc32fast pull request #23
Opened 2021-11-27 06:23 UTC by calmofthestorm

Given `crc(a)`, `crc(b)`, and `len(b)`, you can compute `crc(a || b)`.
The library already supports that via `combine`, but there is not
currently a way to create a `Hasher` with a non-zero `amount` and the
desired state without access to the original data.

2021-11-27 22:40 UTC, srijs requested changes
This is great, thanks so much for the PR!

I have a few smaller change requests, but aside from that it looks good to me! Also props for adding a quickcheck test 👍

2021-11-27 22:40 UTC, srijs commented on src/lib.rs
> +        Self::internal_new_specialized(init, 0)
Instead of duplicating the specialization/baseline constructor logic, could we make a call to the new constructor here, providing `0` as a length?

2021-11-27 22:40 UTC, srijs commented on src/lib.rs
> +    pub fn new_with_initial_length(init: u32, amount: u64) -> Self {
Could we name this `new_with_initial_len`?

Slightly shorter and feels a bit more Rust-y (c.f. `::len` or `::set_len` methods in the stdlib).

2021-11-27 23:44 UTC, calmofthestorm commented
Thanks for taking a look. I have made the requested changes.

2021-11-28 13:57 UTC, srijs commented
Super, thanks for making the changes! Unfortunately it looks like the build is failing because the benchmarks (which use the `internal_new_*` constructors are failing to build. Would you be able to fix that up as well? I think the fuzz testing suite is also using them, and might need adjustment too. Thanks!

2021-11-29 01:07 UTC, calmofthestorm commented
Oops, thanks. I fixed the calls in the fuzz tests and the benchmarks.

2021-11-30 08:01 UTC, merged

2021-11-30 20:37 UTC, srijs commented
Released in `1.3.0` 🎉