Fix AArch64 build when the `nightly` feature is enabled
srijs/rust-crc32fast pull request #36
Opened 2024-05-19 12:11 UTC by AlexTMjugador

https://github.com/rust-lang/stdarch/pull/1573 stabilized the `stdarch_arm_crc32` feature, meaning that it's no longer necessary to enable it to get ARM CRC intrinsics, and doing so in the latest nightlies causes compile errors to happen:

![The described build error](https://github.com/srijs/rust-crc32fast/assets/7822554/fa7bd788-c7c9-48aa-9d9f-14fa7aaac12d)

Let's get rid of that removed unstable feature and update the documentation accordingly.

2024-05-20 12:58 UTC, srijs commented
Hi, thanks for the PR! It's great to see that the feature is finally stabilized.

However, the main issue that I see is that removing the `nightly` guard completely will mean that older rust version (our MSRV is currently 1.46) will then fail to build on `aarch64`.

I've just removed our version detection in fb5bf1632cda72cd67ca0e42ae6db60e5ceff54b, which I'm open to bring back to guard this feature for rust >= 1.80, but I'm also open to other suggestions!

2024-05-20 15:49 UTC, srijs commented
I've published a short term fix in `1.4.2` to make the nightly feature compile again, but what's still missing is moving the `aarch64` CRC32 feature from behind the `nightly` flag to general availability for Rust version >= 1.80.

2024-05-20 16:54 UTC, AlexTMjugador commented
Hi, thanks for the review!

I made the PR in a bit of a hurry and didn't think about older stable Rust version support, sorry.

That being said, if we don't want to bump MSRV at the moment, I think the best we can do is bringing back some form of `rustc` version detection, to only enable AArch64 SIMD intrinsics on versions that have this feature stabilized. Would you mind if I repurpose this PR to do exactly that?

2024-05-20 17:00 UTC, srijs commented
No worries - yep that sounds fine, let's use this PR then for the proper fix 👍

2024-12-02 11:54 UTC, paolobarbolini commented
Is there any chance of this getting merged? Rust 1.84 will stabilize the cargo MSRV aware resolver, so it shouldn't be a problem to bump MSRV since users of older Rust versions will easily be able to use a previous version of this crate.

2025-03-05 18:40 UTC, jrmuizel commented
> Is there any chance of this getting merged? Rust 1.84 will stabilize the cargo MSRV aware resolver, so it shouldn't be a problem to bump MSRV since users of older Rust versions will easily be able to use a previous version of this crate.

Will the MSRV aware resolver help people who are using versions older than 1.84?

2025-03-18 23:04 UTC, eirnym commented
MSRV aware resolver is now stabilized.

2025-03-18 23:04 UTC, eirnym commented
@jrmuizel no, as there's no MSRV aware resolver.

2025-03-18 23:07 UTC, eirnym requested changes

2025-03-18 23:07 UTC, eirnym commented on src/specialized/mod.rs
> +    } else if #[cfg(target_arch = "aarch64")] {
it's still guarded by `crc` feature flag, so I'd keep it.

2025-03-22 20:49 UTC, AlexTMjugador commented on src/specialized/mod.rs
> +    } else if #[cfg(target_arch = "aarch64")] {
It's best not to check for the `crc` target feature here. [The specialized `State` for AArch64 already ensures that these instructions are supported](https://github.com/srijs/rust-crc32fast/blob/479ecdf0174dd3a0f7d48b2f66a386d8d2369963/src/specialized/aarch64.rs#L9-L29), either at runtime or through target features, depending on whether the `std` feature is enabled. If support is lacking in either case, a [fallback to the baseline implementation is done](https://github.com/srijs/rust-crc32fast/blob/479ecdf0174dd3a0f7d48b2f66a386d8d2369963/src/lib.rs#L104-L107). So, adding a target feature check here would render runtime detection useless for targeting AArch64 CPUs with mixed support for these instructions.

2025-03-22 20:55 UTC, AlexTMjugador commented
My apologies for the delayed response on this PR. I got caught up with other stuff, and completely forgot about this PR until its recent notifications reminded me about its existence :sweat_smile: 

I've just implemented the discussed changes to gate the specialized AArch64 `State` behind a sufficiently recent Rust version. This approach sidesteps any need to bump the MSRV, while still allowing newer Rust versions to access the faster implementation by default, without requiring the `nightly` feature.

Please let me know if there's anything else left to do before merging! :rocket:

2025-03-22 21:34 UTC, eirnym approved these changes

2025-06-29 17:52 UTC, closed without merging

2025-06-29 17:52 UTC, srijs commented
Thanks, rebased and merged via #50.